version: '3.8'

services:
  # Сервис для стандартного PHP интерпретатора
  php:
    image: php:8.2-fpm
    container_name: php
    volumes:
      - ./octane:/var/www/html/octane
    networks:
      - webnet

  # Сервис для Swoole
  swoole:
    build: ./swoole
    container_name: swoole
    working_dir: /var/www/html/octane
#    command: php /var/www/html/server.php
    volumes:
      - ./swoole/swoole.conf:/etc/supervisor/service.d/swoole.conf
      - ./server:/var/www/server
      - ./octane:/var/www/html/octane
    ports:
      - "9501:9501" # Порт для Swoole сервера
      - "9502:9502" # Порт для Websocket сервера
    command:
      - php artisan octane:start --port=9502 --server=swoole --host=0.0.0.0 --workers=4
    networks:
      - webnet


  # Сервис для Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./octane:/var/www/html/octane
    ports:
      - "9090:80"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
